### PR TITLE
Use bracket notation for '-moz-force-broken-image-icon'

### PR DESCRIPTION
**Pull request by pyoor**
Fixes https://github.com/mdn/data/issues/429

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Thanks @pyoor . I suppose my question is — can you show me evidence for the square bracket notation part being valid? I mean, `<number>` makes perfect sense, and we have an MDN page for it: https://developer.mozilla.org/en-US/docs/Web/CSS/number

But I've never before come across CSS syntax with the square bracket notation part inside it, and I'm finding it hard to find any information about it. Not to say I don't believe you, but I'd like to learn mroe about it so I can review this PR more effectively ;-)

**Comment by pyoor** [comment]
Bracketed notation was introduced in the [CSS-Values-4 Editors Draft](https://drafts.csswg.org/css-values-4/#numeric-ranges).

**Comment by pyoor** [comment]
I also just realized, this should be `<integer [0,1]>` rather than `<number>` since floating point values are not allowed.

**Comment by chrisdavidmills** [comment]
@pyoor thanks for helping me understand this, and for the further update. This makes sense to me now.

**Pull request merged**
