### PR TITLE
adding aspect-ratio

### PR DESCRIPTION
**Pull request by rachelandrew**
adding the experimental CSS `aspect-ratio` property https://drafts.csswg.org/css-sizing-4/#aspect-ratio

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Looks ok, although the Travis build fails because it doesn't recognise the "appliesTo" value of "allElementsExceptInlineBoxesAndInternalRubyOrTableBoxes". Is it a typo, or does it need adding?

**Comment by rachelandrew** [comment]
I added it as part of this PR, do I need to do it separately?

**Comment by chrisdavidmills** [comment]
Sorry, I didn't notice you'd already added it. Don't know why this failing in that case. Sometimes Travis can be really weird. I've merged it.

**Comment by Elchi3** [comment]
@chrisdavidmills @rachelandrew this PR broke the build, see https://travis-ci.org/mdn/data/builds/610306842?utm_source=github_status&utm_medium=notification

**Comment by Elchi3** [comment]
(not familiar with the mechanics of this repo)
It seems like if you want to use "allElementsExceptInlineBoxesAndInternalRubyOrTableBoxes" you need to declare it here. https://github.com/mdn/data/blob/7c0b46e24b72823e8189280713bbc5228ea89a8b/css/properties.schema.json#L155 and provide a human readable text for it here: https://github.com/mdn/data/blob/8dde448836e82f329ef67217e30861fa84f2af99/l10n/css.json#L183

**Comment by rachelandrew** [comment]
ah right I had added it to css.json but wasn't aware of properties.schema.json. I added it now but not sure I can add to this PR it being closed - should I create a new one?

**Comment by Elchi3** [comment]
Yes, a new PR would be great! Thanks @rachelandrew :+1:

**Comment by chrisdavidmills** [comment]
@Elchi3 thanks for figuring this out.

@rachelandrew I'm fixing it now, so don't worry

**Pull request merged**
