### PR TITLE
Fix display that is not animatable

### PR DESCRIPTION
**Pull request by teoli2003**
Fixes mdn/content#5672

display is not animatable (per test in the issue, and per the spec)

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Maybe somebody from @mdn/core-dev has perms to merge this here?

**Comment by rachelandrew** [comment]
looks like I can :)

**Comment by sideshowbarker** [comment]
> looks like I can :)

🎉 Thanks much

**Comment by teoli2003** [comment]
Cool! Thanks! (I know who to ping next time – I always try not to bother the devs)

**Pull request merged**
