### PR TITLE
Update CSS Fragmentation properties

### PR DESCRIPTION
**Pull request by mfluehr**

### CODE REVIEW

**Comment by lahmatiy** [comment]
@mfluehr You need to add new specs to `css/definitions.json` list

**Comment by mfluehr** [comment]
@lahmatiy Thanks, pull request created for the definitions.

**Comment by lahmatiy** [comment]
I think it's better to do it in this PR. Otherwise checking keeps be failed.

**Comment by mfluehr** [comment]
How do I merge the pull requests together? Sorry, I'm not very good with GitHub.

**Comment by lahmatiy** [comment]
@mfluehr Just push a new commit to your fork's branch `patch-3`

**Pull request closed without merging**
