### PR TITLE
Conicgradient

### PR DESCRIPTION
**Pull request by estelle**
added conic gradient to the gradient list, then added all the new synstax features that make up the conic gradient.

### CODE REVIEW

**Comment by estelle** [comment]
that's so weird. I somehow reverted everything from 
9db25b8  with f280fca.

Crying is much easier than git, but isn't as effective I hear. ugh.

**Comment by estelle** [comment]
Updated. Great catch.

**Comment by chrisdavidmills** [comment]
Nearly there; still need to update `<color-stop>` syntax to `<color-stop-length> | <color-stop-angle>`

**Comment by estelle** [comment]
Updated. Thanks. BTW, I don't think <color-stop> is used anywhere anymore.

**Pull request merged**
