### PR TITLE
Remove HTML entities from syntaxes and related changes (#40)

### PR DESCRIPTION
**Pull request by lahmatiy**
- removed `{ <var>style properties</var> }` from pseudo syntaxes
- replaced `&lt;` to `<`
- replaced `&gt;` to `>`
- replaced `&amp;` to `&`
- replaced `&nbsp;` to ` `
- replaced `<an-plus-b>` for `<nth>` in pseudo selectors
- renamed `<an-plus-b>` for `<nth>` and change its syntax in syntax.json
- added `<an-plus-b>` to types.json
- removed `<var>` from `<minmax>` syntax
- removed `<code>` wrapper in initial values

### CODE REVIEW

**Comment by iamstarkov** [comment]
@lahmatiy do we need to remove html entities from `./css/properties.json` as well?

**Comment by lahmatiy** [comment]
@iamstarkov This PR removes HTML entities from every `json` file in `css` folder

**Comment by iamstarkov** [comment]
correct, thanks

**Comment by Elchi3** [comment]
Reviewing this. This is a massive change, for which MDN/KumaScript macros also need to be prepared for. I'm working on that in mozilla/kumascript#132. We need to review and merge that PR, and deploy it together with this PR then. So please have some patience with us. DO NOT MERGE before.

**Comment by Elchi3** [comment]
> - removed { \<var>style properties\</var> } from pseudo syntaxes

Works for me. @SebastianZ 1) Are you okay with removing this here? 2) If we want to have this back for selector syntax boxes, please let me know in the KumaScript PR.

> - replaced \&lt; to <
> - replaced \&gt; to >
> - replaced \&amp; to &
> - replaced \&nbsp; to

Looks good to me.

> - removed \<code> wrapper in initial value

Looks good to me. @SebastianZ please let me know in the KumaScript PR if we want \<code> back for initial values, it seems like it would work without it for now. (nothing breaks afaik)

Still need to review: 
> - replaced \<an-plus-b> for \<nth> in pseudo selectors
> - renamed \<an-plus-b> for \<nth> and change its syntax in syntax.json
> - added \<an-plus-b> to types.json
> - removed \<var> from \<minmax> syntax

**Comment by SebastianZ** [comment]
>> - removed { \<var>style properties\</var> } from pseudo syntaxes
>
> Works for me. @SebastianZ 1) Are you okay with removing this here? 2) If we want to have this back for selector syntax boxes, please let me know in the KumaScript PR.

I'm ok with that.

>> - replaced \&lt; to <
>> - replaced \&gt; to >
>> - replaced \&amp; to &
>> - replaced \&nbsp; to
>
> Looks good to me.

+1

>> - removed \<code> wrapper in initial value
>
> Looks good to me. @SebastianZ please let me know in the KumaScript PR if we want \<code> back for initial values, it seems like it would work without it for now. (nothing breaks afaik)

I initially added them, because there are a few properties and descriptors that don't have an initial value or a description instead of a value like [`font-family`](https://drafts.csswg.org/css-fonts-3/#font-family-prop) or [`@counter-style/symbols`](https://github.com/mdn/data/blob/9b58cce962e9b099c241948ef1675c9d92782ffe/css/at-rules.json#L93). It needs to be possible to distinguish those from actual initial values.

> - replaced \<an-plus-b> for \<nth> in pseudo selectors
> - renamed \<an-plus-b> for \<nth> and change its syntax in syntax.json
> - added \<an-plus-b> to types.json

Fine for me. Two notes, though:

* This is not part of the spec., but `<an-plus-b>` wasn't, either, so I guess it's ok. This should actually be changed in the spec.
* That requires us to create a page that describes `<an-plus-b>`.

> - removed \<var> from \<minmax> syntax

That change is incorrect, because it now looks like `min` and `max` are keywords. To be correct, it should actually be something like `minmax( [ <length> | <percentage> | <flex> | max-content | min-content | auto ] , [ <length> | <percentage> | <flex> | max-content | min-content | auto ] )`, see the [`minmax()` page](https://developer.mozilla.org/en-US/docs/Web/CSS/minmax).

Sebastian

**Comment by lahmatiy** [comment]
> That requires us to create a page that describes <an-plus-b>.

Worth noting that it described as [the `An+B` microsyntax](https://drafts.csswg.org/css-syntax/#anb-microsyntax) in "CSS Syntax Module Level 3". I'm not sure it should present in `types.json`. It's likely a temporary solution to let us move forward.

> That change is incorrect, because it now looks like min and max are keywords. To be correct, it should actually be something like minmax( [ <length> | <percentage> | <flex> | max-content | min-content | auto ] , [ <length> | <percentage> | <flex> | max-content | min-content | auto ] ), see the minmax() page like you mentioned in issue #40. The spec. is unfortunately incorrect there.

Agree. But while working on PR I found that `minmax()` is using for `fixed-size` and `track-size` with various arguments, and using it directly not as a reference. I see two options here:
- replace `min` and `max` for list of valid values, but in this case the syntax loses clarity (did it for now)
- `minmax` should be removed since it's something abnormal – currently CSS Values and Units grammar can't express this case

**Comment by lahmatiy** [comment]
> I initially added them, because there are a few properties and descriptors that don't have an initial value or a description instead of a value like font-family or @counter-style/symbols. It needs to be possible to distinguish those from actual initial values.

May be add optional property for those cases?

**Comment by lahmatiy** [comment]
@SebastianZ @Elchi3 Friendly reminder :) any progress on PR?

**Comment by lahmatiy** [comment]
@Elchi3 @SebastianZ Any news? Many improvements are pending by this PR...

**Comment by Elchi3** [comment]
Hello @lahmatiy, we are at a MDN team work week and currently not able to review this PR (and the dependency). Please have some extra patience with us.

**Comment by Elchi3** [comment]
I opened https://github.com/mozilla/kumascript/pull/143 which attempts to remove the blocker from our end. Sorry again that this takes a while.

**Comment by Elchi3** [comment]
@SebastianZ can you give this PR an r+? I think I am r+ on it, but I would feel better about merging this, if I have your r+, too. (merge once the MDN blocker is resolved, that is)

**Comment by Elchi3** [comment]
> I opened mozilla/kumascript#143 which attempts to remove the blocker from our end. Sorry again that this takes a while.

This is in MDN production now. We are now using the "mdn" branch from this repository. There is no danger anymore of merging this to master and breaking MDN.

**Comment by Elchi3** [comment]
Thanks so much @lahmatiy! :tada:

**Pull request merged**
