### PR TITLE
Fix small typos in l10n CSS

### PR DESCRIPTION
**Pull request by cw118**
Fixes some typos for Russian (closes mdn/translated-content#3602) and small mistakes for French

### CODE REVIEW

**Comment by myshov** [comment]
👍  for Russian translation

@mdn/yari-content-fr could you review French translations?

**Review by SphinxKnight — APPROVED** [review]
:+1: for @mdn/yari-content-fr as well, thanks for the fix @cw118 and for the ping @myshov :)

**Comment by tanjaslo** [comment]
> 👍 for Russian translation
https://developer.mozilla.org/ru/docs/Web/CSS/grid по этой ссылке нужно ещё
поправить "соответвующему" -> "соответствующему"

**Comment by cw118** [comment]
I can make the changes a little later when I have access to a proper device—might as well fix as many typos as possible here?

**Comment by myshov** [comment]
@cw118 great! There are two typos here:

- (**соответвует** should be **соответствует**) https://github.com/mdn/data/blob/5d0d7dbb98e1de0401ca384924824cce78ad3831/l10n/css.json#L1530
- (**соответвующему** should be **соответствующему**) https://github.com/mdn/data/blob/5d0d7dbb98e1de0401ca384924824cce78ad3831/l10n/css.json#L1239

**Comment by cw118** [comment]
@myshov I've fixed both in my most recent commit, feel free to let me know if there's anything else. 
И спасибо @tanjaslo, что указали на ошибки :)

**Comment by myshov** [comment]
👍for new Russian translations

**Comment by Rumyra** [comment]
Let me know if this is good to go and I'll merge 👍

**Review by SphinxKnight — APPROVED** [review]
LGTM, thanks @cw118 !

**Comment by cw118** [comment]
@mdn/yari-content-ru if possible, could someone please confirm the Russian corrections are good to go?

**Review by sashasushko — APPROVED** [review]

**Comment by cw118** [comment]
Hi @Rumyra, I hope it's alright to ping you — I believe this PR is ready to merge now :)

**Comment by Rumyra** [comment]
@cw118 yes - and thanks :) The package won't publish immediately so there might be a delay until you see the changes just fyi 👍

**Pull request merged**
