### PR TITLE
updating CSS color syntax - alpha-value, hue, rgb(), hsl()...

### PR DESCRIPTION
**Pull request by chrisdavidmills**
to be in line with latest spec changes.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
I'm trying this one again. Can I maybe get @SebastianZ to check it before merge?

**Comment by chrisdavidmills** [comment]
I also added a minor fix to the align-content and justify-content properties, adding the new space-evenly value.

**Comment by Elchi3** [comment]
@SebastianZ: Chris asked me to take a look and I am r+ based on these specs:
https://drafts.csswg.org/css-color-4/#the-hsl-notation
https://drafts.csswg.org/css-color-4/#rgb-functions
https://drafts.csswg.org/css-align/#valdef-align-content-space-evenly
and these bugs
https://bugzilla.mozilla.org/show_bug.cgi?id=1235922
https://bugzilla.mozilla.org/show_bug.cgi?id=1295456

Mats has a few more open points in https://bugzilla.mozilla.org/show_bug.cgi?id=1335106 but Chris and I agreed that these can be handled in new PRs.

**Comment by SebastianZ** [comment]
I'm obviously a bit late on this.

I have several notes:

* The `align-content` and `justify-content` changes don't seem to have a relation to the CSS Color 4 changes, so I wonder why these were done in this patch.
* The patch doesn't include the comma-less new syntax (which also got implemented in [bug 1295456](https://bugzilla.mozilla.org/show_bug.cgi?id=1295456)).
* As far as I can see, `<rgb-component>` is actually not specified and should be replaced by `<percentage>` and `<number>` values (see below).
* Regarding the old and new syntaxes for the `rgb()`, `rgba()`, `hsl()`, and `hsla()` functions, the definitions should actually look something like this:

    ```
    rgb( <percentage>{3} [ / <alpha-value> ]? ) | rgb( <number>{3} [ / <alpha-value> ]? ) |
    rgb( <percentage>#{3} , <alpha-value>? ) | rgb( <number>#{3} , <alpha-value>? )

    rgba( <percentage>{3} [ / <alpha-value> ]? ) | rgb( <number>{3} [ / <alpha-value> ]? ) |
    rgba( <percentage>#{3} , <alpha-value>? ) | rgb( <number>#{3} , <alpha-value>? )

    hsl( <hue> <percentage> <percentage> [ / <alpha-value> ]? ) |
    hsl( <hue>, <percentage>, <percentage>, <alpha-value>? )

    hsla( <hue> <percentage> <percentage> [ / <alpha-value> ]? ) |
    hsla( <hue>, <percentage>, <percentage>, <alpha-value>? )
    ```

    Or they could even be shortened to:

    ```
    rgb(
      [ [ <percentage>{3} | <number>{3} ] [ / <alpha-value> ]? ] |
      [ [ <percentage>#{3} | <number>#{3} ] , <alpha-value>? ]
    )

    rgba(
      [ [ <percentage>{3} | <number>{3} ] [ / <alpha-value> ]? ] |
      [ [ <percentage>#{3} | <number>#{3} ] , <alpha-value>? ]
    )

    hsl(
      [ <hue> <percentage> <percentage> [ / <alpha-value> ]? ] |
      [ <hue>, <percentage>, <percentage>, <alpha-value>? ]
    )

    hsla(
      [ <hue> <percentage> <percentage> [ / <alpha-value> ]? ] |
      [ <hue>, <percentage>, <percentage>, <alpha-value>? ]
    )
    ```

Sebastian

**Comment by Elchi3** [comment]
Thank you Sebastian for reviewing this after the fact.

>  The align-content and justify-content changes don't seem to have a relation to the CSS Color 4 changes, so I wonder why these were done in this patch.

@chrisdavidmills next time please open separate PRs for separate topics.

> The patch doesn't include the comma-less new syntax (which also got implemented in bug 1295456).

I have opened PR #45 with your suggested syntax, anew review appreciated.

> As far as I can see, <rgb-component> is actually not specified and should be replaced by <percentage> and <number> values (see below).

I did not notice the specification had removed this. I will look more closely at the spec syntax next time.

Thanks again.

**Comment by chrisdavidmills** [comment]
Ok, I'll not put unrelated things in patches in future. I just thought that it was a small thing and I wanted to get it done, but yeah, I'll learn from this next time.

As far as the syntax goes, I obviously need to learn more about CSS formal syntax. I just submitted what I thought the spec was actually saying, but I got it wrong. I'll be more careful in future.

Sorry for causing you guys extra work.

Question — if I have already submitted one patch on one branch, is it ok to then go and submit a separate patch on another branch before the first one has been checked and merged?

**Comment by SebastianZ** [comment]
> Question — if I have already submitted one patch on one branch, is it ok to then go and submit a separate patch on another branch before the first one has been checked and merged?

Absolutely. There's no "one PR at a time". 😄 

Sebastian

**Pull request merged**
