### PR TITLE
Translated css.json into Japanese (whose id is between "b" and "n")

### PR DESCRIPTION
**Pull request by mfuji09**
Translated strings whose id is between "b" and "n".
Translated a string "allElementsAndText".
Corrected translations of "allElementsButNonReplacedAndTableColumns" and "autoNonNegativeOrPercentage".

### CODE REVIEW

**Comment by mfuji09** [comment]
This PR has been replaced with https://github.com/mdn/data/pull/460

**Review by chrisdavidmills — COMMENTED** [review]
This is much better, thanks!

**Comment by chrisdavidmills** [comment]
oh, wait, wrong PR...?

**Comment by mfuji09** [comment]
Sorry again! I could translate entire the json file, so I have replaced this with new PR #460 which includes this commit.
Thank you for taking the time!

**Comment by chrisdavidmills** [comment]
> Sorry again! I could translate entire the json file, so I have replaced this with new PR #460 which includes this commit.
> Thank you for taking the time!

No worries — I understand it now ;-)

**Pull request closed without merging**
