### PR TITLE
Add `hanging-punctuation`

### PR DESCRIPTION
**Pull request by mfluehr**

### CODE REVIEW

**Comment by lahmatiy** [comment]
There is no `inlineElements` in `properties.schema.json` for `appliesto` (checking failed). I'm not sure that spec is correct here since value is never used for properties before. On the other hand, it may be correct and that's the first time when such value is needed. In last case a new value for `appliesto` should be added to schema.

**Comment by lahmatiy** [comment]
Reminder: page on MDN should be updated (https://developer.mozilla.org/en-US/docs/Web/CSS/hanging-punctuation) after the changes merge

**Comment by mfluehr** [comment]
Ooh, that's a tricky question about `inlineElements`. What would you recommend? Maybe just list it as "all elements" until the spec gets settled? I have to admit, my comprehension of "Applies to" is fairly limited.

**Comment by lahmatiy** [comment]
Yep, I think it should be "all elements". We can use this value for now and create an issue with question in [spec bug tacker](https://github.com/w3c/csswg-drafts/labels/css-text-3)

**Comment by mfluehr** [comment]
@lahmatiy Ok, the checks are passing now, thanks.

**Comment by mfluehr** [comment]
Spec bug for the correct "applies to" value created here: https://github.com/w3c/csswg-drafts/issues/1833

**Pull request merged**
