### PR TITLE
Add justify-self CSS property

### PR DESCRIPTION
**Pull request by pkuczynski**
Based on:
* https://drafts.csswg.org/css-align-3/#propdef-justify-self
* https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self

Refs #149, https://github.com/csstree/csstree/issues/81

### CODE REVIEW

**Comment by pkuczynski** [comment]
Current issue:

```
  Style – Error on line #4679
    Actual:       "appliesto": ["gridItemsAndBoxesWithinGridContainer", "boxElements"],
    Expected:     "appliesto": [
  JSON Schema – 2 error(s)
    item['justify-self'].groups[0] should be equal to one of the allowed values
    item['justify-self'].appliesto should be equal to one of the allowed values
```

I thought `appliesto` can take an array? Otherwise, I am not sure what to put there. Can anyone help?

**Comment by lahmatiy** [comment]
Just replace it with a single string `blockLevelBoxesAndAbsolutelyPositionedBoxesAndGridItems` (according to [spec draft](https://drafts.csswg.org/css-align-3/#propdef-justify-self)), add this value to `css/properties.schema.json` (at [`applyto` enum](https://github.com/mdn/data/blob/master/css/properties.schema.json#L153)) and add to `l10n/css.json` this section:
```
"blockLevelBoxesAndAbsolutelyPositionedBoxesAndGridItems": {
    "en-US": "block-level boxes, absolutely-positioned boxes, and grid items"
}
```

**Comment by pkuczynski** [comment]
`CSS Box Alignment` group is added in #185

**Comment by pkuczynski** [comment]
Feedback from code review is applied

**Comment by pkuczynski** [comment]
@lahmatiy any luck in re-reviewing it?

**Comment by frenic** [comment]
A friendly reminder to fix the merge conflict due to #184 being merged. Lets hope this can be merged anytime soon.

**Pull request merged**
