### PR TITLE
Extend syntax.json format

### PR DESCRIPTION
**Pull request by lahmatiy**
This PR makes `syntax.json` format uniform with other dictionaries. Also, this make it possible to extend the description of the syntaxes in the future.
Changes based on #41

### CODE REVIEW

**Comment by lahmatiy** [comment]
@Elchi3 Why not to merge? 😞

**Comment by Elchi3** [comment]
@lahmatiy Sorry, I should have left an explanation here. We can't merge this now, because MDN relies on the old structure. It is a breaking change and I don't have the time to patch MDN just now. We want to merge this, but later when MDN is patched, or we have published a package and this is in a later version, which MDN doesn't load then. Please have some patience.

**Comment by Elchi3** [comment]
This needs a rebase and changes to the schema now. I'll try to unblock us on the MDN/KumaScript side.

**Comment by lahmatiy** [comment]
@Elchi3 Done
I've used latest `css/syntax.json` and converted it with a script.

**Comment by Elchi3** [comment]
Thanks @lahmatiy! We still need to wait for https://github.com/mozilla/kumascript/pull/208 to get merged and deployed.

Also it says there is a conflict, can you resolve that or should I?

**Comment by lahmatiy** [comment]
@Elchi3 Conflict is fixed.

**Comment by lahmatiy** [comment]
@Elchi3 mozilla/kumascript#208 is merged. Are there no blockers now?

**Comment by jwhitlock** [comment]
Merged, but please wait until mozilla/kumascript#208 is deployed, or you'll break MDN.  I'm planning on deploying tomorrow morning (in 15 hours or so)

**Comment by jwhitlock** [comment]
Deployed to staging and production. @Elchi3, ready for merging and manual testing.

**Pull request merged**
