### PR TITLE
removing certain contributions as part of relicensing plan

### PR DESCRIPTION
**Pull request by chrisdavidmills**
Here we are removing certain contributions to allow us to complete our plan to relicense the repo to CC0 (see https://github.com/mdn/data/issues/240 for more context).

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
So I removed angle, but I think AsAngleBasicshapeOrPath was already updated to angleOrBasicShapeOrPath. I therefore removed that one instead.

**Comment by chrisdavidmills** [comment]
I've looked for dependencies on those...I think that's about it?

**Comment by wbamberg** [comment]
It should also be removed from the schema: https://github.com/mdn/data/search?q=angleOrBasicShapeOrPath. Sorry!

**Comment by wbamberg** [comment]
>  I believe offset-path is already removed, so the instance in the properties.json file is not there?

Yes, I think that's already removed in this PR: https://github.com/mdn/data/pull/294/files#diff-55f6403f7fb454999a3f946361507bdeL6164 although the diffs are confusing.

**Comment by octref** [comment]
Can I ask why brackets are escaped here?
Also, can these removed properties be brought back?

**Comment by chrisdavidmills** [comment]
@octref I don't really know why brackets were escaped. That is a bit strange.

I have added back a few of the removed properties already, in https://github.com/mdn/data/pull/309. Happy to add others back.

**Pull request merged**
