### PR TITLE
Issue 31: Removed 'document-url' keyword from <content-list> syntax

### PR DESCRIPTION
**Pull request by SebastianZ**

### CODE REVIEW

**Comment by Elchi3** [comment]
@SebastianZ this now needs a rebase?! I think Chris merged something directly into master...

@teoli2003 can you review?

**Comment by SebastianZ** [comment]
> @SebastianZ this now needs a rebase?! I think Chris merged something directly into master...

Let's first revert Chris' changes, as his patch obviously changed more than what was intended. See https://github.com/mdn/data/pull/38.

Sebastian

**Comment by SebastianZ** [comment]
@teoli2003 The corrupt patch is reverted, so this one applies cleanly again. So, please have a look.

Sebastian

**Comment by Elchi3** [comment]
Thanks, this looks good to me.

**Comment by SebastianZ** [comment]
Thanks for merging! I'm just wondering what happened with Jean-Yves' review.

Sebastian

**Pull request merged**
