### PR TITLE
Add `content-visibility` property

### PR DESCRIPTION
**Pull request by frenic**
https://www.w3.org/TR/css-contain-2/#content-visibility

Related https://github.com/frenic/csstype/pull/120

### CODE REVIEW

**Review by artem-malko — APPROVED** [review]

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
Looks pretty good, thanks @frenic !

One query though — shouldn't the `status` be `standard` ?

**Comment by frenic** [comment]
I choose `nonstandard` because it was a working draft. But really I'm not sure what defines the status in this case. I would love to hear more about how you reason about it.

However, I changed it to `standard`. Thanks!

**Comment by frenic** [comment]
Is this OK to merge now?

**Comment by chrisdavidmills** [comment]
Yes, absolutely. Sorry, I thought I'd done this one!

**Comment by chrisdavidmills** [comment]
And to answer your previous question, generally we say something is a standard if it is somewhere on a standards track, and has some kind of momentum/interest. This page contains our "official" definitions of when to document something, what experimental means, etc: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Conventions_definitions

It's a tricky question though, and I'm still not sure they are 100% perfect.

**Comment by frenic** [comment]
> And to answer your previous question, generally we say something is a standard if it is somewhere on a standards track, and has some kind of momentum/interest. This page contains our "official" definitions of when to document something, what experimental means, etc: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Conventions_definitions
> 
> It's a tricky question though, and I'm still not sure they are 100% perfect.

That info help out a lot! Thanks 🙂

**Pull request merged**
