### PR TITLE
Update syntaxes to match latest specs

### PR DESCRIPTION
**Pull request by scheinercc**
Update border-style, border-width, outline-style and outline-width; bug 1340159

### CODE REVIEW

**Comment by Elchi3** [comment]
Thanks, this looks better!
I think you will need to update the corresponding syntax definitions in https://github.com/mdn/data/blob/master/css/syntaxes.json as well. It currently references `<br-style>` for example.

**Comment by scheinercc** [comment]
@Elchi3 Thanks for pointing me in the right direction. Now checking syntaxes.json and comparing the corresponding specs for my change I might have overdone it with this change a little ... maybe. Let me explain, it could be simpler than I suspect:
[Bug 1340159](https://bugzilla.mozilla.org/show_bug.cgi?id=1340159)'s title reads _"Rename &lt;br-style> to &lt;line-style> in border-style page"_. While going through properties.json it seemed obvious to me to also apply the changes for other `border-style` properties, like  `border-top-style`, etc. Subsequently I saw that pretty much the same update was required for `border-width` from `<br-width>` to `<line-width>`. Lastly I found `<br-style>` and `<br-width>` for `outline-style` and `outline-width`.
Though now for the change required in syntaxes.json, the specs of the later two confuse me. For example the value for [`outline-style`](https://drafts.csswg.org/css-ui-3/#outline-style) is `<border-style>`, which links to the `<border-style>` property which has the value `<line-style>`.
Would that for the MDN article on [`outline-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/outline-style#Formal_syntax) the formal syntax reads:

> ...
> where
> &lt;border-style> = none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset

or 

> ...
> where
> &lt;line-style> = none | hidden | dotted | dashed | solid | double | groove | ridge | inset | outset

Any idea?

**Comment by teoli2003** [comment]
Yes <border-style> for outline-style is not correct. It should be <'border-style'> or <line-style>{1,4}
The same w/ <border-width> for outline-border.

I would prefer avoiding an indirection and have <line-style>{1,4} and <line-width>{1,4} there.

**Comment by scheinercc** [comment]
> I would prefer avoiding an indirection and have {1,4} and {1,4} there.

Sorry, but what does that mean? Can you elaborate on this a little?

**Comment by teoli2003** [comment]
Sorry. I meant:
I prefer to have <line-style>{1,4} rather than <'border-style'> or <border-style>.

**Comment by scheinercc** [comment]
@teoli2003 I don't understand the code change required here. Will hand over the task to the next one who wants to work on it.

**Comment by scheinercc** [comment]
Done. Thanks for picking this up @wbamberg 💯

**Comment by wbamberg** [comment]
First, @scheinercc , thanks for your work on this! I think part of the reason some of the review comments were so confusing was that the comments didn't escape the "\<" in things like "\<line-style>", so parts of the comments got eaten. I've edited some of the comments to add escapes, so they make more sense now.

I've made a few updates to your changes, they are in this commit: https://github.com/mdn/data/pull/104/commits/a4d26df08003fb5c96cf452f79c208dcaba4872a. In particular, I've:

* updated the syntax for `border`, where it looks like you missed a `<br-width>`
* updated `outline-style` and `outline-width`. Note that I've chosen to define `outline-style` as `auto | <'border-style'>`, contrary to @teoli2003 's https://github.com/mdn/data/pull/104#issuecomment-335099901. This is because [the spec has `auto | <border-style>`](https://drafts.csswg.org/css-ui-3/#outline-style), which I think is wrong (see https://github.com/mdn/data/pull/104#issuecomment-334714447) but `<'border-style'>` is closer to the spec, and I've tried to keep as close as I can to the spec.
* added `<line-style>` and `<line-width>` to syntaxes.json, and removed `<br-style>` and `<br-width>`

Rendered using csssyntax.ejs, it looks like this:

screen shot 2018-09-11 at 14 54 55-fullpage

**Comment by wbamberg** [comment]
@Elchi3 , would you mind taking a look?

**Pull request merged**
