### PR TITLE
Add `shape-box` data type

### PR DESCRIPTION
**Pull request by mfluehr**
This data type is used in the `shape-outside` property.

### CODE REVIEW

**Comment by teoli2003** [comment]
I disagree on this one. <shape-box> is not a fundamental CSS types used everyone. It is a syntactical type used for technical reasons and defined in syntaxes.json L512.

I would not make a specific article for it, I would simply list all the keywords and their meaning in shape-outside.

**Comment by mfluehr** [comment]
Thanks for the response, @teoli2003 . The article already exists (created in 2014): https://developer.mozilla.org/en-US/docs/Web/CSS/shape-box . Do you want to delete it, and remove the link to it found in https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside ?

**Comment by teoli2003** [comment]
Thank for your help, mfluehr!

I think we should:
1) Integrate the info from the shape-box page into shape-outside (no <shape-box> should appear under the sections 'Values'
2) Redirect the shape-box page to shape-outside.

**Comment by mfluehr** [comment]
Alright, I've updated those two pages per your recommendations. Closing this pull request.

**Pull request closed without merging**
