### PR TITLE
Updated 'display' property syntax according to CSS Display 3

### PR DESCRIPTION
**Pull request by SebastianZ**
This patch updates the `display` CSS property's syntax according to the one [defined in the CSS Display Module Level 3 spec.](https://drafts.csswg.org/css-display-3/#the-display-properties), but also includes the [`subgrid` keyword as defined in the CSS Grid Layout Module Level 1 spec](https://drafts.csswg.org/css-grid/#grid-containers).

This change is done in relation to [bug 1322191](https://bugzilla.mozilla.org/show_bug.cgi?id=1322191).

Sebastian

### CODE REVIEW

**Comment by Elchi3** [comment]
@teoli2003 can you review?

**Comment by Elchi3** [comment]
This looks good to me and the CSS Display specification has the same syntax. https://drafts.csswg.org/css-grid/#grid-containers adds `grid` and `subgrid` and you've decided to add it to `<display-inside> ` and `inline-grid` to `<display-legacy>`. I don't know enough about CSS to judge whether or not this classification is correct. I assume it is, as https://developer.mozilla.org/en-US/docs/Web/CSS/display has been reviewed by others, too, and it appears there as well.

**Comment by SebastianZ** [comment]
> https://drafts.csswg.org/css-grid/#grid-containers adds `grid` and `subgrid` and you've decided to add it to `<display-inside> ` and `inline-grid` to `<display-legacy>`. The definition in CSS Grid is obviously redundant.

Sebastian

That's what is defined in the [CSS Display spec.](https://drafts.csswg.org/css-display-3/#typedef-display-inside)

**Comment by SebastianZ** [comment]
As this is a bigger change, I'd still like to have a review of @teoli2003.

Sebastian

**Comment by Elchi3** [comment]
> That's what is defined in the CSS Display spec. The definition in CSS Grid is obviously redundant.

OK, was not obvious to me then ;-)

**Comment by teoli2003** [comment]
I have one concern: the spec and this syntax adds new valid values that are not implemented by any browser. It looks to me that this syntax will be useless to understand was display: can actually have as values.

@SebastianZ @elchi3 Shouldn't we describe real syntax rather than theoretical ones?

**Comment by SebastianZ** [comment]
Sorry for the long delay on this!

I think it is ok to use the new syntax, as long as we explain that browsers currently only support one keyword as value.
@teoli2003 Please note that the [`display` page](https://developer.mozilla.org/en-US/docs/Web/CSS/display) itself already got updated to reflect the CSS Display 3 spec. It's just missing the info about the one-keyword support.

Sebastian

**Comment by Elchi3** [comment]
Here is my take on complex information:

There is data (this repo) that we want to have as correct and comprehensive as possible for all kinds of consumers. Then there is MDN consuming this data, too, and offering documentation about CSS. MDN is free to display data in a way that is good for web developers (also by omitting it, presenting it differently, or otherwise modifying it). For example, imo, the display page should get renewed to be an overview page about what the display property can do generally. And then sub pages could talk about display values in more details with visual examples. But that, again, is and MDN docs question, not an MDN data question. For the data itself, we should also talk about implementation reality and not the specification theory world, but we are trying to be as precise and complete as possible. As specs and implementations are often close, we can go with what the spec says in most cases.

Does that make sense?

**Comment by Elchi3** [comment]
To avoid merge conflicts for issue #40, is this good to go? @SebastianZ @teoli2003

**Comment by SebastianZ** [comment]
Yes, splitting the page explaining the `display` property is a good idea, which was [already requested by Jean-Yves](https://bugzilla.mozilla.org/show_bug.cgi?id=1120964) earlier. The article is just too long and too complex at the moment. (Btw. the [same applies to the `<input>` page](https://bugzilla.mozilla.org/show_bug.cgi?id=861235), which actually already has some subpages, but still needs to be simplified.)

And I also agree with you that the data should be correct and comprehensive. Having said that, as we display the syntax on MDN, we have three options to do that:

* Use the syntax from the specs and explain the different values, even when they are not implemented yet.
* Use the syntax from the specs and remove the unsupported parts from it before displaying it.
* Use the syntax from the specs, output it as is and accept that it may differ from implementations and not describe the unimplemented parts.
* Adjust the syntax to the one that fits implementations and only describe that syntax.

I am obviously for the first solution, as it is the most complete one and allows to explain the differences between the specs and implementations. This also allows us to advocate for upcoming features. Having said that. Though, of course, this has the cost of having to change the descriptions and syntaxes more often, as parts may be changed more frequently.

That's a lot of meta-discussion, so to be concrete, the differences of the `display` values in implementations and the spec. are the multi-value syntaxes `[ <display-outside> || <display-inside> ]` and `list-item && <display-outside>? && [ flow | flow-root ]?` and the `inline-list-item`, `flow`, and `subgrid` keywords. I think those differences can be explained easily (and partially already are).

So, I'm still for merging the changes. Then we should split up the `display` page.

Sebastian

**Comment by Elchi3** [comment]
I'm merging this. I think we agree and I this will avoid merge conflicts for incoming larger PRs (#40, #41)

**Pull request merged**
