### PR TITLE
feat: update syntax for Anchor Positioning related properties

### PR DESCRIPTION
**Pull request by skyclouds2001**
### Description

https://drafts.csswg.org/css-anchor-position-1/#anchor-size-fn for `anchor-size()`
https://drafts.csswg.org/css-anchor-position-1/#position-anchor for `position-anchor`

### CODE REVIEW

**Review by KEEFER82 — COMMENTED** [review]
css/functions.json

**Review by pepelsbey — COMMENTED** [review]
Looks good, apart from a little detail: the element reference is called `<anchor-name>` in the spec but we call it `<anchor-element>`. Is there a reason for that? They might’ve renamed it recently, too.

**Comment by skyclouds2001** [comment]
it seems to be so when the data is added via https://github.com/mdn/data/pull/728 by @chrisdavidmills ,and at that time it is `<anchor-element>`

it has changed to `<anchor-name>` which happens at https://github.com/w3c/csswg-drafts/commit/1d18c6a86099b158ddc9adb50e7e75f8990d0207 recently, this seems to be a simple rename

**Review by pepelsbey — APPROVED** [review]
Great! Thank you :)

**Comment by chrisdavidmills** [comment]
Thanks a lot for this, @skyclouds2001. I've created a PR at https://github.com/mdn/content/pull/36424 to make the equivalent updates in the content repo.

**Comment by chrisdavidmills** [comment]
@pepelsbey, can you merge this one? I don't have the necessary privs, unfortunately.

**Pull request merged**
